name = "nexora"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "cc7e9ee0fca126669777efec6a072232"

[vars]
ENVIRONMENT = "production"
PAGES_ORIGIN = "https://nexora-a8m.pages.dev"
API_ORIGIN = "https://nexora-bvc-api-2026.vkola306.workers.dev"
