// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmw8HgHrgh6o9qXB2-vVM4D_K1Q_Wm6o',
    appId: '1:1056749020398:android:0aa8026219e4c3a20f3fff',
    messagingSenderId: '1056749020398',
    projectId: 'nexorabvcai',
    storageBucket: 'nexorabvcai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfEZZ8Yo3J5PmHMU-fX0tyLtCg-YnlHw',
    appId: '1:1056749020398:ios:4cd574fb4628d6580f3fff',
    messagingSenderId: '1056749020398',
    projectId: 'nexorabvcai',
    storageBucket: 'nexorabvcai.firebasestorage.app',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMI7UxOrVxb9E8GBavhNA60-DA5_54Tcw',
    appId: '1:1056749020398:web:ab4abc8a5f6397120f3fff',
    messagingSenderId: '1056749020398',
    projectId: 'nexorabvcai',
    authDomain: 'nexorabvcai.firebaseapp.com',
    storageBucket: 'nexorabvcai.firebasestorage.app',
    measurementId: 'G-DGS0GLHWKQ',
  );
}
