name = "nexora-bvc-api-2026"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
ADMIN_SECRET = "nexora-admin-secure-key-2026"

[[d1_databases]]
binding = "DB"
database_name = "nexora-rag"
database_id = "nexora-rag"
